This is  404 not found page
7T4-DevPlus/Client_OJT7T4 pull request #17
Opened 2023-12-11 06:52 UTC by thanhsondev

This is  404 not found page. Websites often use the HTTP error code 404 to tell users that the page they tried to access could not be found on the server. This could be for a variety of reasons, including the URL being wrong, the page being deleted or moved, or there being a technical error on the site.

2023-12-11 13:46 UTC, luanvo1910 commented
chụp thêm hình ảnh page cho mn coi với

2023-12-11 13:50 UTC, luanvo1910 requested changes

2023-12-11 13:50 UTC, luanvo1910 commented on src/pages/404notfound/PageNotFound.jsx
sao ko lấy thẳng url của ảnh mà fetch chi rườm rà z :v

2023-12-11 13:50 UTC, luanvo1910 commented on .idea/.gitignore
mấy file trong .idea là gì v, sao tạo thêm 1 file .gitignore nữa

2023-12-12 02:09 UTC, thanhsondev commented
\
![Screenshot 2023-12-12 090810](https://github.com/7T4-DevPlus/Client_OJT7T4/assets/132500171/d2c1a170-7664-4620-8bb8-de86924afa58)

2023-12-15 10:32 UTC, closed without merging